#!/usr/bin/env python3
"""Measure what each rule costs and catches, and keep the records that depend on it current.

    python3 tools/rule_evidence.py            # print the table, most review cost first
    python3 tools/rule_evidence.py --write    # store the figures: each rule's evidence field in slop_rules.json,
                                              # and the genre table in tests/human/README.md

Cost: findings on the human corpus in tests/human (speeches, a style guide, blog posts, commit messages, UI strings
and three kinds of email, all written before chat models) under the shipped default profile. Every one of them is a
sentence a person would have to read and then keep or change, so a rule that fires often there costs review time
without catching machine writing. Catch: the must_flag fixture lines that name the rule, and how many of those it
flags. The genre table uses the corpus test's settings (typography on, house style off).

run_tests.py fails when either record is out of date, so run this with --write after any rule change.

These are false-alarm and coverage figures on fixed sets. They do not show that a rule improves anyone's writing;
that needs labeled human drafts and before-and-after review (see tests/blind/README.md).
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.dont_write_bytecode = True
import speakhuman_lint as sl  # noqa: E402

HUMAN = os.path.join(ROOT, "tests", "human")
HUMAN_README = os.path.join(HUMAN, "README.md")
MUST_FLAG = os.path.join(ROOT, "tests", "fixtures", "must_flag.md")
EXPECT_RE = re.compile(r"<!--\s*expect:\s*([^>]*?)\s*-->")
MARK = "measured: "
# Kept on the maintainer's machine and out of the public repository (see tests/human/README.md). The suite runs the
# genre when the file is there; the generated table and evidence leave it out, so they match on every machine.
LOCAL_ONLY = {"business email": "enron-sent-mail.json"}
TABLE_START, TABLE_END = "<!-- genre-table: generated by tools/rule_evidence.py -->", "<!-- /genre-table -->"


def corpus_profile():
    """The settings the corpus test runs with: typography rules on, house style off."""
    return dict(sl.PROFILE_DEFAULTS, ascii_only=True, disable_classes=["house_style"])


def human_genres():
    """The human corpus by genre: {genre: [Doc, ...]}. run_tests.py uses the same split for its ceilings."""
    def read(path):
        return sl.read_doc(os.path.relpath(path, HUMAN), open(path, encoding="utf-8").read())
    top = sorted(n for n in os.listdir(HUMAN) if n.endswith((".md", ".txt")) and n != "README.md")
    blog = os.path.join(HUMAN, "18f-blog")
    genres = {
        "speeches and a style guide": [read(os.path.join(HUMAN, n)) for n in top],
        "blog posts": [read(os.path.join(blog, n)) for n in sorted(os.listdir(blog)) if n.endswith(".md")],
        "commit messages": [sl.read_doc("<stdin>", m, "plain")
                            for m in json.load(open(os.path.join(HUMAN, "login-gov-commits.json"), encoding="utf-8"))],
        "UI strings": [read(os.path.join(HUMAN, "login-gov-ui.en.json"))],
        "transactional email": [read(os.path.join(HUMAN, "login-gov-email.en.json"))],
        "agency email": [sl.read_doc(n, open(os.path.join(HUMAN, "agency-email", n), encoding="utf-8").read(), "plain")
                         for n in sorted(os.listdir(os.path.join(HUMAN, "agency-email"))) if n.endswith(".txt")],
    }
    for genre, name in LOCAL_ONLY.items():
        path = os.path.join(HUMAN, name)
        if os.path.exists(path):
            genres[genre] = [sl.read_doc("<stdin>", m, "plain") for m in json.load(open(path, encoding="utf-8"))]
    return genres


def public_genres():
    return {g: docs for g, docs in human_genres().items() if g not in LOCAL_ONLY}


def human_docs():
    for docs in public_genres().values():
        yield from docs


def genre_rows():
    """[(genre, words, errors per 1000, warnings per 1000)] under the corpus test's settings."""
    rules = sl.load_rules(profile=corpus_profile())
    rows = []
    for genre, docs in public_genres().items():
        e = w = words = 0
        for doc in docs:
            words += sl.doc_words(doc)
            for f in sl.lint_doc(doc, rules, {"mode": "density", "min": 2}):
                e += f.severity == "error"
                w += f.severity == "warn"
        rows.append((genre, words, 1000.0 * e / max(1, words), 1000.0 * w / max(1, words)))
    return rows


def genre_table():
    lines = ["| Genre | Words | Errors per 1,000 | Warnings per 1,000 |", "|---|---:|---:|---:|"]
    lines += ["| %s | %s | %.2f | %.2f |" % (g[:1].upper() + g[1:], format(n, ","), e, w) for g, n, e, w in genre_rows()]
    return "\n".join(lines)


def evidence_lines():
    """{rule id: the evidence line for that rule} under the shipped default profile."""
    prof = dict(sl.PROFILE_DEFAULTS)
    rules = sl.load_rules(profile=prof)
    pol = {"mode": prof["device_policy"], "min": prof["device_min"], "scope": prof["device_scope"]}
    cost, words = {}, 0
    for doc in human_docs():
        words += sl.doc_words(doc)
        for f in sl.lint_doc(doc, rules, pol):
            if f.severity != "info":
                c = cost.setdefault(f.rule, {"error": 0, "warn": 0})
                c[f.severity] += 1
    src = open(MUST_FLAG, encoding="ascii").read()
    found = {}
    for f in sl.lint_doc(sl.read_doc(MUST_FLAG, src), rules, pol):
        if f.severity != "info":
            found.setdefault(f.line, set()).add(f.rule)
    named, caught = {}, {}
    for li, line in enumerate(src.split("\n"), start=1):
        m = EXPECT_RE.search(line)
        if not m:
            continue
        for rid in (w.strip() for w in m.group(1).split(",")):
            named[rid] = named.get(rid, 0) + 1
            caught[rid] = caught.get(rid, 0) + (rid in found.get(li, set()))
    out = {}
    for r in rules:
        if r.kind == "manual":
            continue
        c = cost.get(r.id, {"error": 0, "warn": 0})
        line = "%s%d finding(s) (%d error, %d warning) in %s words of human writing from before chat models " \
               "(tests/human, default profile)" % (MARK, c["error"] + c["warn"], c["error"], c["warn"], format(words, ","))
        if named.get(r.id):
            line += "; flags %d of %d must_flag cases that name it" % (caught[r.id], named[r.id])
        out[r.id] = (c["error"] + c["warn"], caught.get(r.id, 0), named.get(r.id, 0), words, line)
    return out


def main(argv):
    ev = evidence_lines()
    words = next(iter(ev.values()))[3] if ev else 0
    print("%-34s %8s %6s %10s" % ("rule", "per 1000", "hits", "must_flag"))
    for rid, (n, ca, na, _, _) in sorted(ev.items(), key=lambda kv: (-kv[1][0], kv[0])):
        if n or na:
            print("%-34s %8.2f %6d %10s" % (rid, 1000.0 * n / max(1, words), n, "%d/%d" % (ca, na) if na else "-"))
    print("human corpus: %s words" % format(words, ","))
    print(genre_table())
    if "--write" in argv:
        data = json.load(open(sl.RULES_PATH, encoding="utf-8"))
        for r in data["rules"]:
            if r["id"] in ev:
                r["evidence"] = [e for e in (r.get("evidence") or []) if not e.startswith(("measured ", MARK))] + [ev[r["id"]][4]]
        open(sl.RULES_PATH, "w", encoding="utf-8").write(json.dumps(data, indent=1, ensure_ascii=True))
        text = open(HUMAN_README, encoding="utf-8").read()
        a, b = text.index(TABLE_START), text.index(TABLE_END)
        open(HUMAN_README, "w", encoding="utf-8").write(text[:a + len(TABLE_START)] + "\n" + genre_table() + "\n" + text[b:])
        print("wrote evidence for %d rules and the genre table" % len(ev))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
